cask_args appdir: '/Applications'
tap 'argon/mas'
tap 'caskroom/cask'
tap 'caskroom/fonts'
tap 'caskroom/versions'
tap 'homebrew/binary'
tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'homebrew/versions'
tap 'oppara/homebrew'
tap 'peco/peco'
cask 'java'
brew 'pkg-config'
brew 'libyaml'
brew 'openssl'
brew 'ansible'
brew 'autoconf'
brew 'xz'
brew 'automake'
brew 'awscli'
brew 'bfg'
brew 'pcre'
brew 'gettext'
brew 'git', args: ['with-pcre']
brew 'go'
brew 'ccat'
brew 'nkf'
brew 'cmigemo'
brew 'cpanminus'
brew 'ctags'
brew 'direnv'
brew 'findutils', args: ['with-default-names']
brew 'fpp'
brew 'libpng'
brew 'freetype'
brew 'gdbm'
brew 'ghq'
brew 'gibo'
brew 'gnu-getopt'
brew 'git-now'
brew 'gmp'
brew 'gnu-sed', args: ['with-default-names']
brew 'hub'
brew 'libtool'
brew 'jpeg'
brew 'libtiff'
brew 'imagemagick'
brew 'ipcalc'
brew 'oniguruma'
brew 'jq'
brew 'libevent'
brew 'lua'
brew 'luajit'
brew 'lv'
brew 'readline'
brew 'sqlite'
brew 'python'
brew 'mercurial'
brew 'mysql'
brew 'node'
brew 'node-build'
brew 'nspr'
brew 'pandoc'
brew 'peco'
brew 'perl-build'
brew 'phantomjs'
brew 'plenv'
brew 'postgresql'
brew 'q'
brew 'ruby-build'
brew 'rbenv'
brew 'reattach-to-user-namespace', args: ['with-wrap-launchctl', 'with-wrap-pbcopy-and-pbpaste']
brew 'subversion'
brew 'the_platinum_searcher'
brew 'the_silver_searcher'
brew 'tig'
brew 'tmux'
brew 'tree'
brew 'unar'
brew 'vim', args: ['with-lua', 'with-luajit']
brew 'wget'
brew 'zsh', args: ['without-etcdir']
brew 'zsh-completions'
brew 'argon/mas/mas'
brew 'homebrew/binary/jsl'
brew 'oppara/homebrew/kcode'
brew 'oppara/homebrew/wcwidth'
brew 'peco/peco/migemogrep'
cask '0xed'
cask 'alfred'
cask 'appcleaner'
cask 'betterzipql'
cask 'clipmenu'
cask 'docker'
cask 'fenix'
cask 'firefox-ja'
cask 'font-hack'
cask 'font-migu-2m'
cask 'gitter'
cask 'google-chrome'
cask 'karabiner'
cask 'launchrocket'
cask 'liteicon'
cask 'macs-fan-control'
cask 'mplayerx'
cask 'qlcolorcode'
cask 'qlmarkdown'
cask 'qlprettypatch'
cask 'qlstephen'
cask 'quicklook-csv'
cask 'quicklook-json'
cask 'spamsieve'
cask 'suspicious-package'
cask 'the-unarchiver'
cask 'transmission'
cask 'transmit'
cask 'vagrant'
cask 'vagrant-manager'
cask 'virtualbox'
cask 'vlc'
cask 'webpquicklook'
cask 'youtube-to-mp3'
mas 'Simplenote', id: 692867256
mas 'WinArchiver Lite', id: 414855915
mas 'Kindle', id: 405399194
mas 'Translate App', id: 936484167
mas 'Twitter', id: 409789998
mas 'Skitch', id: 425955336
mas 'Kobito', id: 896624060
mas '1Password', id: 443987910
mas 'StuffIt Expander', id: 405580712
mas 'Witch', id: 412485838
mas 'Xcode', id: 497799835
mas 'Reeder', id: 880001334
mas 'Numbers', id: 409203825
mas 'CotEditor', id: 1024640650
mas 'Dash', id: 458034879
