tap 'argon/mas'
tap 'caskroom/cask'
tap 'caskroom/fonts'
tap 'caskroom/versions'
tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'oppara/homebrew'
tap 'rcmdnk/rcmdnkpac'
tap 'genkiroid/homebrew-cert'

brew 'ansible'
brew 'argon/mas/mas'
brew 'autoconf'
brew 'automake'
brew 'awscli'
brew 'ask-cli'
brew 'bat'
brew 'bfg'
brew 'ccat'
brew 'cert'
brew 'cfn-lint'
brew 'cloc'
brew 'cmigemo'
brew 'cpanminus'
brew 'ctags'
brew 'dep'
brew 'direnv'
brew 'docker-compose-completion'
brew 'docker-machine-completion'
brew 'emojify'
brew 'expect'
brew 'findutils', args: ['with-default-names']
brew 'fpp'
brew 'freetype'
brew 'gdbm'
brew 'gettext'
brew 'ghq'
brew 'gibo'
brew 'git', args: ['with-pcre']
brew 'git-lfs'
brew 'git-now'
brew 'git-open'
brew 'git-secrets'
brew 'glide'
brew 'gmp'
brew 'gnu-getopt'
brew 'gnu-sed', args: ['with-default-names']
brew 'go'
brew 'httpie'
brew 'hub'
brew 'imagemagick'
brew 'ipcalc'
brew 'jo'
brew 'jpeg'
brew 'jq'
brew 'libevent'
brew 'libpng'
brew 'libtiff'
brew 'libtool'
brew 'libxml2'
brew 'libxslt'
brew 'libyaml'
brew 'libzip'
brew 'lua'
brew 'luajit'
brew 'lv'
brew 'mysql'
brew 'nkf'
brew 'node'
brew 'nspr'
brew 'oniguruma'
brew 'openssl'
brew 'oppara/homebrew/kcode'
brew 'oppara/homebrew/keyboardswitcher'
brew 'oppara/homebrew/wcwidth'
brew 'pandoc'
brew 'pcre'
brew 'pkg-config'
brew 'postgresql'
brew 'python'
brew 'q'
brew 'rcmdnk/rcmdnkpac/parse-plist'
brew 'readline'
brew 'reattach-to-user-namespace', args: ['with-wrap-launchctl', 'with-wrap-pbcopy-and-pbpaste']
brew 'rga'
brew 'ripgrep'
brew 'shfmt'
brew 'sqlite'
brew 'subversion'
brew 'the_platinum_searcher'
brew 'the_silver_searcher'
brew 'tig'
brew 'tmux', args: ['with-utf8proc']
brew 'tree'
brew 'unar'
brew 'vagrant-completion'
brew 'vim'
brew 'wget'
brew 'xz'
brew 'yamllint'
brew 'zplug'
brew 'zsh', args: ['without-etcdir']
brew 'zsh-completions'

cask '0xed'
cask 'alfred'
cask 'appcleaner'
cask 'betterzipql'
cask 'colorpicker-plus'
cask 'docker'
cask 'fenix'
cask 'firefox'
cask 'font-cica'
cask 'font-migu-2m'
cask 'gitter'
cask 'glance'
cask 'google-chrome'
cask 'hammerspoon'
cask 'java'
cask 'launchrocket'
cask 'liteicon'
cask 'macs-fan-control'
cask 'maczip4win'
cask 'onyx'
cask 'psequel'
cask 'qlcolorcode'
cask 'qlimagesize'
cask 'qlmarkdown'
cask 'qlprettypatch'
cask 'qlstephen'
cask 'quicklook-csv'
cask 'quicklook-json'
cask 'sequel-pro-nightly'
cask 'session-manager-plugin'
cask 'skype'
cask 'slack'
cask 'spamsieve'
cask 'suspicious-package'
cask 'table-tool'
cask 'the-unarchiver'
cask 'transmit'
cask 'vagrant'
cask 'vagrant-manager'
cask 'virtualbox'
cask 'webpquicklook'
cask 'transmission'
cask 'mplayerx'
cask 'youtube-to-mp3'
cask 'vlc'

mas 'Kindle', id: 405399194
mas 'StuffIt Expander', id: 405580712
mas 'Skitch', id: 425955336
mas '1Password', id: 443987910
mas 'Witch', id: 412485838
mas 'Reeder', id: 880001334
mas 'CotEditor', id: 1024640650
mas 'Dash', id: 458034879
mas 'Kobito', id: 896624060
mas 'Simplenote', id: 692867256
